### ISSUE TITLE
Running this on own Server

### ISSUE THREAD

**Issue by chrisrwebb** [opsgenie/opsgenie-connectwise-integration#1]
Hi 

I tried support but I am not entirely sure I got the correct answer. The readme suggests that this can be run on any WEB backed. If I have it running on my own server do I just point the integration URL to the index.js file?

Thanks,

Chris

**Comment by serhatcan** [comment]
Hi @chrisrwebb ,
> You can capture related alert actions at any WEB backend. Here, we demonstrate how you can do it over AWS Lambda.

This means that you can implement it for your own server application and this code is an example of how it can be done with AWS Lambda. 

You can just use express.js to create your own node.js web server if you want. Most of the parts will be the same. You may need to convert the data accordingly to reuse the already implemented functionality.  (Also, you can do it with other languages as this is a webhook based integration, you just need a web server)

PS. The statement looks a bit misleading, so we will change it.

I hope it helps!
